### ISSUE TITLE
missing packages

### ISSUE THREAD

**Issue by PeerHerholz** [neuropower/neurodesign#3]
Ahoi there,

I just wanted to try neurodesign and installed it via pip (pip install neurodesign).
After trying to import the package I got several errors related to missing modules.
More precisely: reportlab, pdfrw and progressbar.  
After installing the respective modules everything worked fine.

In case it isn't specific for my set up: maybe the modules could be included as dependencies!? 

Thanks for this great tool!

Best, Peer

**Comment by lewisdunne** [comment]
Just bumping this - tried the import and I also experience missing packages. Any idea how I can fix this?

**Comment by PeerHerholz** [comment]
Hi @lewisdunne,

if you're missing the same packages you can just `pip install` them, which should be the 
case for most other missing dependencies as well.

HTH, cheers, Peer

**Comment by lewisdunne** [comment]
Hi @PeerHerholz , it isn't the same unfortunately. After looking closer at it I realise it seems like it is actually missing functions rather than missing packages. I'm not quite sure how to overcome that:

```
Traceback (most recent call last):

  File "<ipython-input-1-fde4081bad59>", line 1, in <module>
    import neurodesign

  File "C:\Users\L\Anaconda3\lib\site-packages\neurodesign\__init__.py", line 8, in <module>
    from neurodesign import design, experiment, optimisation

ImportError: cannot import name 'design' from 'neurodesign' (C:\Users\L\Anaconda3\lib\site-packages\neurodesign\__init__.py)
```

**Comment by PeerHerholz** [comment]
Hi @lewisdunne,

I think there were some python2.*/3.* thingies going on. Through the changes in this [PR](https://github.com/neuropower/neurodesign/pull/9), they appear to be resolved. At least the imports seem to work now.

**Comment by PeerHerholz** [comment]
Hi @lewisdunne,

as far as I can tell, everything I've done (and way more) has been implemented in a [PR](https://github.com/neuropower/neurodesign/pull/8) from last year that hasn't been merged yet.

**Comment by lewisdunne** [comment]
Ok, I'll just wait and keep an eye out for updates then. Thanks

**Comment by Remi-Gau** [comment]
installing from master should be fixed

will try to push to pypi soon
